// Code generated by protoc-gen-go. DO NOT EDIT.
// source: answer.proto

package xmit

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Answer struct {
	ServerIp             uint32   `protobuf:"varint,1,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	ServerPort           uint32   `protobuf:"varint,2,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	TimeoutMs            uint32   `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Credentials          []byte   `protobuf:"bytes,4,opt,name=credentials,proto3" json:"credentials,omitempty"`
	Transport            int32    `protobuf:"varint,5,opt,name=transport,proto3" json:"transport,omitempty"`
	Carry                []byte   `protobuf:"bytes,6,opt,name=carry,proto3" json:"carry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Answer) Reset()         { *m = Answer{} }
func (m *Answer) String() string { return proto.CompactTextString(m) }
func (*Answer) ProtoMessage()    {}
func (*Answer) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f97dbee99679ee, []int{0}
}

func (m *Answer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Answer.Unmarshal(m, b)
}
func (m *Answer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Answer.Marshal(b, m, deterministic)
}
func (m *Answer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Answer.Merge(m, src)
}
func (m *Answer) XXX_Size() int {
	return xxx_messageInfo_Answer.Size(m)
}
func (m *Answer) XXX_DiscardUnknown() {
	xxx_messageInfo_Answer.DiscardUnknown(m)
}

var xxx_messageInfo_Answer proto.InternalMessageInfo

func (m *Answer) GetServerIp() uint32 {
	if m != nil {
		return m.ServerIp
	}
	return 0
}

func (m *Answer) GetServerPort() uint32 {
	if m != nil {
		return m.ServerPort
	}
	return 0
}

func (m *Answer) GetTimeoutMs() uint32 {
	if m != nil {
		return m.TimeoutMs
	}
	return 0
}

func (m *Answer) GetCredentials() []byte {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *Answer) GetTransport() int32 {
	if m != nil {
		return m.Transport
	}
	return 0
}

func (m *Answer) GetCarry() []byte {
	if m != nil {
		return m.Carry
	}
	return nil
}

func init() {
	proto.RegisterType((*Answer)(nil), "xmit.protocol.Answer")
}

func init() { proto.RegisterFile("answer.proto", fileDescriptor_c6f97dbee99679ee) }

var fileDescriptor_c6f97dbee99679ee = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xbd, 0x6a, 0xc3, 0x30,
	0x10, 0x80, 0x51, 0x6b, 0x8b, 0xfa, 0x6c, 0x2f, 0xa2, 0x83, 0xa0, 0x2d, 0x15, 0x9d, 0x3c, 0x75,
	0xc9, 0x13, 0x24, 0x5b, 0x86, 0x40, 0xf0, 0x98, 0xc5, 0x28, 0x8e, 0x06, 0x81, 0x6d, 0x89, 0xd3,
	0xe5, 0xef, 0xd9, 0xf2, 0x72, 0x21, 0x92, 0x21, 0xd9, 0xee, 0xbe, 0x8f, 0x3b, 0xf8, 0xa0, 0xd2,
	0x53, 0x38, 0x1b, 0xfc, 0xf7, 0xe8, 0xc8, 0x89, 0xfa, 0x32, 0x5a, 0x4a, 0x73, 0xef, 0x86, 0xbf,
	0x1b, 0x03, 0xbe, 0x8c, 0x5e, 0x7c, 0x41, 0x11, 0x0c, 0x9e, 0x0c, 0x76, 0xd6, 0x4b, 0xa6, 0x58,
	0x53, 0xb7, 0x1f, 0x09, 0xac, 0xbd, 0xf8, 0x85, 0x72, 0x96, 0xde, 0x21, 0xc9, 0xb7, 0xa8, 0x21,
	0xa1, 0xad, 0x43, 0x12, 0x3f, 0x00, 0x64, 0x47, 0xe3, 0x8e, 0xd4, 0x8d, 0x41, 0xbe, 0x47, 0x5f,
	0xcc, 0x64, 0x13, 0x84, 0x82, 0xb2, 0x47, 0x73, 0x30, 0x13, 0x59, 0x3d, 0x04, 0x99, 0x29, 0xd6,
	0x54, 0xed, 0x2b, 0x12, 0xdf, 0x50, 0x10, 0xea, 0x29, 0xc4, 0xff, 0xb9, 0x62, 0x4d, 0xde, 0x3e,
	0x81, 0xf8, 0x84, 0xbc, 0xd7, 0x88, 0x57, 0xc9, 0xe3, 0x65, 0x5a, 0x56, 0x7c, 0x97, 0x3d, 0x72,
	0xf6, 0x3c, 0xf6, 0x2c, 0xee, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x59, 0xeb, 0x49, 0xeb, 0x00,
	0x00, 0x00,
}
