// Code generated by protoc-gen-go. DO NOT EDIT.
// source: init.proto

package xmit

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitReq_Serializer int32

const (
	InitReq_kProtobuf3 InitReq_Serializer = 0
)

var InitReq_Serializer_name = map[int32]string{
	0: "kProtobuf3",
}

var InitReq_Serializer_value = map[string]int32{
	"kProtobuf3": 0,
}

func (x InitReq_Serializer) String() string {
	return proto.EnumName(InitReq_Serializer_name, int32(x))
}

func (InitReq_Serializer) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{0, 0}
}

type InitRep_Serializer int32

const (
	InitRep_kProtobuf3 InitRep_Serializer = 0
)

var InitRep_Serializer_name = map[int32]string{
	0: "kProtobuf3",
}

var InitRep_Serializer_value = map[string]int32{
	"kProtobuf3": 0,
}

func (x InitRep_Serializer) String() string {
	return proto.EnumName(InitRep_Serializer_name, int32(x))
}

func (InitRep_Serializer) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{1, 0}
}

type InitReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitReq) Reset()         { *m = InitReq{} }
func (m *InitReq) String() string { return proto.CompactTextString(m) }
func (*InitReq) ProtoMessage()    {}
func (*InitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{0}
}

func (m *InitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitReq.Unmarshal(m, b)
}
func (m *InitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitReq.Marshal(b, m, deterministic)
}
func (m *InitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitReq.Merge(m, src)
}
func (m *InitReq) XXX_Size() int {
	return xxx_messageInfo_InitReq.Size(m)
}
func (m *InitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InitReq.DiscardUnknown(m)
}

var xxx_messageInfo_InitReq proto.InternalMessageInfo

type InitRep struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRep) Reset()         { *m = InitRep{} }
func (m *InitRep) String() string { return proto.CompactTextString(m) }
func (*InitRep) ProtoMessage()    {}
func (*InitRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{1}
}

func (m *InitRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRep.Unmarshal(m, b)
}
func (m *InitRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRep.Marshal(b, m, deterministic)
}
func (m *InitRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRep.Merge(m, src)
}
func (m *InitRep) XXX_Size() int {
	return xxx_messageInfo_InitRep.Size(m)
}
func (m *InitRep) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRep.DiscardUnknown(m)
}

var xxx_messageInfo_InitRep proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("xmit.protocol.InitReq_Serializer", InitReq_Serializer_name, InitReq_Serializer_value)
	proto.RegisterEnum("xmit.protocol.InitRep_Serializer", InitRep_Serializer_name, InitRep_Serializer_value)
	proto.RegisterType((*InitReq)(nil), "xmit.protocol.InitReq")
	proto.RegisterType((*InitRep)(nil), "xmit.protocol.InitRep")
}

func init() { proto.RegisterFile("init.proto", fileDescriptor_8d036da5b4a9bcf3) }

var fileDescriptor_8d036da5b4a9bcf3 = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcc, 0xcb, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xad, 0xc8, 0x85, 0xb1, 0x93, 0xf3, 0x73, 0x94,
	0xd4, 0xb9, 0xd8, 0x3d, 0xf3, 0x32, 0x4b, 0x82, 0x52, 0x0b, 0x95, 0x64, 0xb8, 0xb8, 0x82, 0x53,
	0x8b, 0x32, 0x13, 0x73, 0x32, 0xab, 0x52, 0x8b, 0x84, 0xf8, 0xb8, 0xb8, 0xb2, 0x03, 0x40, 0xaa,
	0x92, 0x4a, 0xd3, 0x8c, 0x05, 0x18, 0x10, 0x0a, 0x0b, 0xf0, 0x2b, 0x74, 0x62, 0x8b, 0x62, 0x01,
	0x59, 0x91, 0xc4, 0x06, 0xb6, 0xc3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x48, 0x96, 0x39, 0x39,
	0x7d, 0x00, 0x00, 0x00,
}
