// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consts.proto

package xmit

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transport int32

const (
	Transport_kUdp Transport = 0
	Transport_kWdc Transport = 1
)

var Transport_name = map[int32]string{
	0: "kUdp",
	1: "kWdc",
}

var Transport_value = map[string]int32{
	"kUdp": 0,
	"kWdc": 1,
}

func (x Transport) String() string {
	return proto.EnumName(Transport_name, int32(x))
}

func (Transport) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c7beb262b56b3db8, []int{0}
}

type Role int32

const (
	Role_kClient Role = 0
	Role_kServer Role = 1
)

var Role_name = map[int32]string{
	0: "kClient",
	1: "kServer",
}

var Role_value = map[string]int32{
	"kClient": 0,
	"kServer": 1,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c7beb262b56b3db8, []int{1}
}

type Mode int32

const (
	Mode_kNoneReliable          Mode = 0
	Mode_kFullReliable          Mode = 1
	Mode_kSemiReliableUnordered Mode = 2
	Mode_kSemiReliableOrdered   Mode = 3
)

var Mode_name = map[int32]string{
	0: "kNoneReliable",
	1: "kFullReliable",
	2: "kSemiReliableUnordered",
	3: "kSemiReliableOrdered",
}

var Mode_value = map[string]int32{
	"kNoneReliable":          0,
	"kFullReliable":          1,
	"kSemiReliableUnordered": 2,
	"kSemiReliableOrdered":   3,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}

func (Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c7beb262b56b3db8, []int{2}
}

type Priority int32

const (
	Priority_kLow      Priority = 0
	Priority_kNormal   Priority = 1
	Priority_kHigh     Priority = 2
	Priority_kCritical Priority = 3
)

var Priority_name = map[int32]string{
	0: "kLow",
	1: "kNormal",
	2: "kHigh",
	3: "kCritical",
}

var Priority_value = map[string]int32{
	"kLow":      0,
	"kNormal":   1,
	"kHigh":     2,
	"kCritical": 3,
}

func (x Priority) String() string {
	return proto.EnumName(Priority_name, int32(x))
}

func (Priority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c7beb262b56b3db8, []int{3}
}

type ControlType int32

const (
	ControlType_kInitReq ControlType = 0
	ControlType_kInitRsp ControlType = 1
	ControlType_kPing    ControlType = 2
	ControlType_kPong    ControlType = 3
	ControlType_kError   ControlType = 4
	ControlType_kAck     ControlType = 5
	ControlType_kNak     ControlType = 6
	ControlType_kFec     ControlType = 7
)

var ControlType_name = map[int32]string{
	0: "kInitReq",
	1: "kInitRsp",
	2: "kPing",
	3: "kPong",
	4: "kError",
	5: "kAck",
	6: "kNak",
	7: "kFec",
}

var ControlType_value = map[string]int32{
	"kInitReq": 0,
	"kInitRsp": 1,
	"kPing":    2,
	"kPong":    3,
	"kError":   4,
	"kAck":     5,
	"kNak":     6,
	"kFec":     7,
}

func (x ControlType) String() string {
	return proto.EnumName(ControlType_name, int32(x))
}

func (ControlType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c7beb262b56b3db8, []int{4}
}

func init() {
	proto.RegisterEnum("xmit.protocol.Transport", Transport_name, Transport_value)
	proto.RegisterEnum("xmit.protocol.Role", Role_name, Role_value)
	proto.RegisterEnum("xmit.protocol.Mode", Mode_name, Mode_value)
	proto.RegisterEnum("xmit.protocol.Priority", Priority_name, Priority_value)
	proto.RegisterEnum("xmit.protocol.ControlType", ControlType_name, ControlType_value)
}

func init() { proto.RegisterFile("consts.proto", fileDescriptor_c7beb262b56b3db8) }

var fileDescriptor_c7beb262b56b3db8 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcd, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x93, 0x36, 0x4d, 0xdb, 0x69, 0x0b, 0xe3, 0x22, 0x22, 0x5e, 0xf4, 0x9c, 0x83, 0x17,
	0x8f, 0x9e, 0xb4, 0x58, 0x14, 0xb4, 0x96, 0x7e, 0x20, 0x78, 0x4b, 0x93, 0xa1, 0x2e, 0xbb, 0xdd,
	0x89, 0x93, 0xf5, 0xa3, 0xff, 0xbd, 0xb8, 0x8d, 0x8a, 0xb7, 0xdf, 0x7b, 0x0f, 0x66, 0x1e, 0x0f,
	0x86, 0x05, 0xbb, 0xda, 0xd7, 0xe7, 0x95, 0xb0, 0x67, 0x35, 0xfa, 0xdc, 0x6a, 0xbf, 0xe7, 0x82,
	0x6d, 0x76, 0x0a, 0xfd, 0xa5, 0xe4, 0xae, 0xae, 0x58, 0xbc, 0xea, 0x41, 0x62, 0x56, 0x65, 0x85,
	0x51, 0xa0, 0xa7, 0xb2, 0xc0, 0x38, 0x3b, 0x83, 0x64, 0xce, 0x96, 0xd4, 0x00, 0xba, 0x66, 0x6c,
	0x35, 0x39, 0x8f, 0x51, 0x10, 0x0b, 0x92, 0x77, 0x12, 0x8c, 0xb3, 0x35, 0x24, 0x0f, 0x5c, 0x92,
	0x3a, 0x80, 0x91, 0x99, 0xb2, 0xa3, 0x39, 0x59, 0x9d, 0xaf, 0x2d, 0x61, 0x14, 0xac, 0xc9, 0x9b,
	0xb5, 0xbf, 0x56, 0xac, 0x4e, 0xe0, 0xc8, 0x2c, 0x68, 0xab, 0x7f, 0xac, 0x95, 0x63, 0x29, 0x49,
	0xa8, 0xc4, 0x96, 0x3a, 0x86, 0xc3, 0x7f, 0xd9, 0x63, 0x93, 0xb4, 0xb3, 0x4b, 0xe8, 0xcd, 0x44,
	0xb3, 0x68, 0xbf, 0x0b, 0xdd, 0xee, 0xf9, 0xa3, 0xa9, 0x31, 0x65, 0xd9, 0xe6, 0x16, 0x63, 0xd5,
	0x87, 0x8e, 0xb9, 0xd5, 0x9b, 0x17, 0x6c, 0xa9, 0x11, 0xf4, 0xcd, 0x58, 0xb4, 0xd7, 0x45, 0x6e,
	0xb1, 0x9d, 0x69, 0x18, 0x8c, 0xd9, 0x79, 0x61, 0xbb, 0xdc, 0x55, 0xa4, 0x86, 0xd0, 0x33, 0x77,
	0x4e, 0xfb, 0x39, 0xbd, 0x62, 0xf4, 0xa7, 0xea, 0xaa, 0x39, 0x32, 0xd3, 0x6e, 0x83, 0xad, 0x3d,
	0xb2, 0xdb, 0x60, 0x5b, 0x01, 0xa4, 0xe6, 0x46, 0x84, 0x05, 0x93, 0xf0, 0xfd, 0xaa, 0x30, 0xd8,
	0x09, 0x34, 0xcd, 0x0d, 0xa6, 0x81, 0x26, 0x54, 0x60, 0xf7, 0x3a, 0x7d, 0x4e, 0xbe, 0xf7, 0x5d,
	0xa7, 0x61, 0xe0, 0x8b, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10, 0xab, 0x0d, 0x1c, 0x7c, 0x01,
	0x00, 0x00,
}
